name: Test
run-name: Testing
on:
  workflow_dispatch:
    inputs:
      preset:
        type: string
        default: "default-tkg"
        description: Wine preset
      version:
        type: string
        description: Wine version
jobs:
  beep-boop:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update
          sudo apt-get install libkrb5-dev libxpresent-dev
          sudo sed -i -e 's/-flto=auto -ffat-lto-objects -flto=auto //' /usr/bin/krb5-config.mit
          sudo apt-get install libkrb5-dev:i386 libxpresent-dev:i386
      - name: Check out
        uses: actions/checkout@v2
        with:
          repository: 'Frogging-Family/wine-tkg-git'
      - name: Configure
        working-directory: ./wine-tkg-git
        run: |
          sed -i -e 's/distro=""/distro="debuntu"/' -e "/_LOCAL_PRESET/s/\x22\x22/\x22${{ inputs.preset }}\x22/" -e "/_plain_version/s/\x22\x22/\x22${{ inputs.version }}\x22/" -e "/_staging_version/s/\x22\x22/\x22v${{ inputs.version }}\x22/" customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
          ./non-makepkg-build.sh --deps64
          ./non-makepkg-build.sh --deps32
